import type { Continent } from "@/db/schema";

export type CountryEntry = { slug: string; label: string; continent: Continent };

const RAW: [string, string, Continent][] = [
  // North America
  ["usa", "United States", "north-america"],
  ["canada", "Canada", "north-america"],
  ["mexico", "Mexico", "north-america"],
  ["guatemala", "Guatemala", "north-america"],
  ["belize", "Belize", "north-america"],
  ["honduras", "Honduras", "north-america"],
  ["el-salvador", "El Salvador", "north-america"],
  ["nicaragua", "Nicaragua", "north-america"],
  ["costa-rica", "Costa Rica", "north-america"],
  ["panama", "Panama", "north-america"],
  ["cuba", "Cuba", "north-america"],
  ["jamaica", "Jamaica", "north-america"],
  ["haiti", "Haiti", "north-america"],
  ["dominican-republic", "Dominican Republic", "north-america"],
  ["puerto-rico", "Puerto Rico", "north-america"],
  ["bahamas", "Bahamas", "north-america"],
  // South America
  ["brazil", "Brazil", "south-america"],
  ["argentina", "Argentina", "south-america"],
  ["chile", "Chile", "south-america"],
  ["uruguay", "Uruguay", "south-america"],
  ["paraguay", "Paraguay", "south-america"],
  ["bolivia", "Bolivia", "south-america"],
  ["peru", "Peru", "south-america"],
  ["ecuador", "Ecuador", "south-america"],
  ["colombia", "Colombia", "south-america"],
  ["venezuela", "Venezuela", "south-america"],
  ["guyana", "Guyana", "south-america"],
  ["suriname", "Suriname", "south-america"],
  // Europe
  ["united-kingdom", "United Kingdom", "europe"],
  ["ireland", "Ireland", "europe"],
  ["france", "France", "europe"],
  ["spain", "Spain", "europe"],
  ["portugal", "Portugal", "europe"],
  ["andorra", "Andorra", "europe"],
  ["italy", "Italy", "europe"],
  ["switzerland", "Switzerland", "europe"],
  ["austria", "Austria", "europe"],
  ["germany", "Germany", "europe"],
  ["netherlands", "Netherlands", "europe"],
  ["belgium", "Belgium", "europe"],
  ["luxembourg", "Luxembourg", "europe"],
  ["liechtenstein", "Liechtenstein", "europe"],
  ["denmark", "Denmark", "europe"],
  ["norway", "Norway", "europe"],
  ["sweden", "Sweden", "europe"],
  ["finland", "Finland", "europe"],
  ["iceland", "Iceland", "europe"],
  ["estonia", "Estonia", "europe"],
  ["latvia", "Latvia", "europe"],
  ["lithuania", "Lithuania", "europe"],
  ["poland", "Poland", "europe"],
  ["czechia", "Czechia", "europe"],
  ["slovakia", "Slovakia", "europe"],
  ["hungary", "Hungary", "europe"],
  ["slovenia", "Slovenia", "europe"],
  ["croatia", "Croatia", "europe"],
  ["bosnia-and-herzegovina", "Bosnia and Herzegovina", "europe"],
  ["serbia", "Serbia", "europe"],
  ["montenegro", "Montenegro", "europe"],
  ["albania", "Albania", "europe"],
  ["north-macedonia", "North Macedonia", "europe"],
  ["greece", "Greece", "europe"],
  ["bulgaria", "Bulgaria", "europe"],
  ["romania", "Romania", "europe"],
  ["moldova", "Moldova", "europe"],
  ["ukraine", "Ukraine", "europe"],
  ["belarus", "Belarus", "europe"],
  ["malta", "Malta", "europe"],
  ["cyprus", "Cyprus", "europe"],
  ["turkey", "Türkiye", "europe"],
  // Asia
  ["georgia", "Georgia", "asia"],
  ["armenia", "Armenia", "asia"],
  ["azerbaijan", "Azerbaijan", "asia"],
  ["russia", "Russia", "asia"],
  ["kazakhstan", "Kazakhstan", "asia"],
  ["uzbekistan", "Uzbekistan", "asia"],
  ["kyrgyzstan", "Kyrgyzstan", "asia"],
  ["tajikistan", "Tajikistan", "asia"],
  ["turkmenistan", "Turkmenistan", "asia"],
  ["mongolia", "Mongolia", "asia"],
  ["china", "China", "asia"],
  ["japan", "Japan", "asia"],
  ["south-korea", "South Korea", "asia"],
  ["taiwan", "Taiwan", "asia"],
  ["india", "India", "asia"],
  ["pakistan", "Pakistan", "asia"],
  ["nepal", "Nepal", "asia"],
  ["bhutan", "Bhutan", "asia"],
  ["bangladesh", "Bangladesh", "asia"],
  ["sri-lanka", "Sri Lanka", "asia"],
  ["myanmar", "Myanmar", "asia"],
  ["thailand", "Thailand", "asia"],
  ["laos", "Laos", "asia"],
  ["cambodia", "Cambodia", "asia"],
  ["vietnam", "Vietnam", "asia"],
  ["malaysia", "Malaysia", "asia"],
  ["singapore", "Singapore", "asia"],
  ["indonesia", "Indonesia", "asia"],
  ["philippines", "Philippines", "asia"],
  ["israel", "Israel", "asia"],
  ["jordan", "Jordan", "asia"],
  ["lebanon", "Lebanon", "asia"],
  ["iran", "Iran", "asia"],
  ["iraq", "Iraq", "asia"],
  ["saudi-arabia", "Saudi Arabia", "asia"],
  ["uae", "United Arab Emirates", "asia"],
  ["oman", "Oman", "asia"],
  ["yemen", "Yemen", "asia"],
  ["kuwait", "Kuwait", "asia"],
  ["qatar", "Qatar", "asia"],
  // Africa
  ["morocco", "Morocco", "africa"],
  ["tunisia", "Tunisia", "africa"],
  ["algeria", "Algeria", "africa"],
  ["libya", "Libya", "africa"],
  ["egypt", "Egypt", "africa"],
  ["sudan", "Sudan", "africa"],
  ["ethiopia", "Ethiopia", "africa"],
  ["kenya", "Kenya", "africa"],
  ["uganda", "Uganda", "africa"],
  ["tanzania", "Tanzania", "africa"],
  ["rwanda", "Rwanda", "africa"],
  ["zambia", "Zambia", "africa"],
  ["zimbabwe", "Zimbabwe", "africa"],
  ["botswana", "Botswana", "africa"],
  ["namibia", "Namibia", "africa"],
  ["south-africa", "South Africa", "africa"],
  ["lesotho", "Lesotho", "africa"],
  ["eswatini", "Eswatini", "africa"],
  ["mozambique", "Mozambique", "africa"],
  ["malawi", "Malawi", "africa"],
  ["madagascar", "Madagascar", "africa"],
  ["angola", "Angola", "africa"],
  ["ghana", "Ghana", "africa"],
  ["senegal", "Senegal", "africa"],
  ["ivory-coast", "Ivory Coast", "africa"],
  ["nigeria", "Nigeria", "africa"],
  ["cameroon", "Cameroon", "africa"],
  // Oceania
  ["australia", "Australia", "oceania"],
  ["new-zealand", "New Zealand", "oceania"],
  ["fiji", "Fiji", "oceania"],
  ["papua-new-guinea", "Papua New Guinea", "oceania"],
];

export const COUNTRIES: CountryEntry[] = RAW.map(([slug, label, continent]) => ({
  slug,
  label,
  continent,
}));

const ALIASES: Record<string, string> = {
  "united-states": "usa",
  "united-states-of-america": "usa",
  america: "usa",
  "u-s": "usa",
  "u-s-a": "usa",
  us: "usa",
  "great-britain": "united-kingdom",
  england: "united-kingdom",
  scotland: "united-kingdom",
  wales: "united-kingdom",
  holland: "netherlands",
  "czech-republic": "czechia",
  macedonia: "north-macedonia",
  emirates: "uae",
  turkiye: "turkey",
  korea: "south-korea",
};

export function countryBySlug(slug: string): CountryEntry | undefined {
  return COUNTRIES.find((entry) => entry.slug === slug);
}

export function normalizeCountrySlug(raw: string): string {
  const input = raw.toLowerCase().trim();
  if (!input) return "";
  if (ALIASES[input]) return ALIASES[input];
  if (COUNTRIES.some((entry) => entry.slug === input)) return input;
  return input;
}
