# Asia (10) + Oceania (10)
RIDES2 = [
    ("manali-leh-highway", "Manali to Leh Highway", "asia", "india", "himachal-pradesh", None,
     300, 12.0, "Mountain Passes", "mountain", 5, "Jun – Sep",
     "Five passes above 13,000 ft between Kullu valley and Ladakh. Stream crossings and cold mornings; acclimatize, do not race the altitude.",
     [("Manali", 32.24, 77.19), ("Sarchu", 32.91, 77.62), ("Leh", 34.16, 77.58)]),
    ("pangong-ladakh", "Ladakh Pangong Approach", "asia", "india", "ladakh", None,
     90, 3.5, "Mountain Passes", "mountain", 5, "Jun – Sep",
     "Chang La at 17,590 ft then a barren moonscape down to the brackish Pangong lake. Carry papers; the road is army-controlled.",
     [("Karu, Ladakh", 34.0, 77.6), ("Chang La", 34.03, 77.88), ("Tangtse", 33.87, 78.09)]),
    ("hai-van-pass", "Hai Van Pass", "asia", "vietnam", "da-nang", None,
     13, 0.7, "Coastal Cruise", "coastal", 3, "Feb – Aug",
     "The ocean wall between Da Nang and Lang Co bay. Fog bank at the pass and seller kids at the summit viewpoint.",
     [("Da Nang", 16.05, 108.21), ("Hai Van summit", 16.18, 108.19), ("Lang Co", 16.28, 108.19)]),
    ("mae-hong-son-loop", "Mae Hong Son Loop", "asia", "thailand", "mae-hong-son", None,
     400, 12.0, "Hairpin Heaven", "mixed", 4, "Nov – Feb",
     "1,864 curves through the Shan hills between Chiang Mai and Mae Hong Son. Do it clockwise over three days.",
     [("Chiang Mai", 18.79, 98.98), ("Pai", 19.3, 98.44), ("Mae Hong Son", 19.3, 97.83)]),
    ("venus-line", "Venus Line", "asia", "japan", "nagano", None,
     35, 1.5, "Mountain Passes", "mountain", 3, "May – Oct",
     "A highland skyline road from Utsukushigahara to Suwa. Wildflower meadows at 2,000 meters and glass-smooth tarmac.",
     [("Ueda, Nagano", 36.4, 138.25), ("Utsukushigahara", 36.34, 138.1), ("Chino", 36.03, 138.15)]),
    ("bandai-azuma-skyline", "Bandai-Azuma Skyline", "asia", "japan", "fukushima", None,
     28, 1.2, "Mountain Passes", "mountain", 3, "May – Oct",
     "Volcanic terrain above Fukushima city, past the Azuma crater rim. The Tsutsujo parking area has the best ridge line view.",
     [("Fukushima city", 37.75, 140.47), ("Azuma crater rim", 37.63, 140.5), ("Takayu Onsen", 37.75, 140.42)]),
    ("sun-moon-lake-loop", "Sun Moon Lake Loop", "asia", "taiwan", "nantou", None,
     35, 1.5, "Scenic Chill", "mixed", 2, "Year-round",
     "Ride the lake rim at sunrise before the tour buses. Tunnel exits open to the water with perfect timing.",
     [("Puli, Nantou", 23.97, 120.97), ("Sun Moon Lake", 23.86, 120.9), ("Shuishe", 23.87, 120.91)]),
    ("shimanami-kaido", "Shimanami Kaido", "asia", "japan", "ehime", None,
     44, 2.0, "Coastal Cruise", "coastal", 2, "Mar – Nov",
     "Island-hop the Seto Inland Sea on the Kurushima-Kaikyo bridge chain. Ferris-wheel views and salt-water wind the whole run.",
     [("Onomichi, Hiroshima", 34.41, 133.19), ("Imabari, Ehime", 33.83, 132.98), ("Omi-shima", 34.26, 133.0)]),
    ("gangwon-coast-run", "Gangwon Coast Run", "asia", "south-korea", "gangwon", None,
     130, 4.0, "Coastal Cruise", "coastal", 2, "May – Oct",
     "Route 7 hugs the East Sea with fishing towns and tunnel after tunnel. Yangyang surf breaks are the lunch stop.",
     [("Gangneung", 37.75, 128.9), ("Yangyang", 38.07, 128.6), ("Sokcho", 38.2, 128.6)]),
    ("bali-north-coast-loop", "Bali North Coast Loop", "asia", "indonesia", "bali", None,
     140, 5.0, "Twisty & Technical", "mixed", 3, "Apr – Nov",
     "Over the Buleleng ridges to Lovina's black-sand coast and back through Munduk's waterfalls. Scooters outnumber cars up here.",
     [("Seminyak, Bali", -8.69, 115.16), ("Bedugul", -8.25, 115.16), ("Lovina", -8.16, 115.04)]),

    # ─── OCEANIA (10) ───
    ("great-ocean-road", "Great Ocean Road", "oceania", "australia", "victoria", None,
     150, 5.0, "Coastal Cruise", "coastal", 2, "Year-round",
     "The Twelve Apostles from the saddle of a bike. Lorne to Apollo Bay is the ribbon everyone talks about.",
     [("Torquay, VIC", -38.3, 144.3), ("Lorne", -38.53, 143.97), ("Apollo Bay", -38.76, 143.67)]),
    ("grand-pacific-drive", "Grand Pacific Drive", "oceania", "australia", "new-south-wales", None,
     90, 3.0, "Coastal Cruise", "coastal", 2, "Year-round",
     "The Sea Cliff Bridge hangs off the Illawarra escarpment over the ocean. Ride it north to south for the sun at your back.",
     [("Sydney, NSW", -33.86, 151.21), ("Stanwell Tops", -34.34, 150.97), ("Wollongong", -34.43, 150.89)]),
    ("great-alpine-road", "Great Alpine Road", "oceania", "australia", "victoria", None,
     190, 5.0, "Mountain Passes", "mountain", 4, "Nov – Apr",
     "Australia's highest sealed road over Mount Hotham. Dinner Plain and Omeo make a perfect day loop from Bright.",
     [("Bright", -36.73, 146.96), ("Mount Hotham", -37.01, 147.14), ("Omeo", -37.1, 147.59)]),
    ("reef-drive-port-douglas", "Great Barrier Reef Drive", "oceania", "australia", "queensland", None,
     75, 2.5, "Coastal Cruise", "coastal", 2, "May – Oct",
     "Captain Cook Highway hugs the rainforest edge between Cairns and Port Douglas. Watch for cassowaries north of Mossman.",
     [("Cairns, QLD", -16.92, 145.77), ("Palm Cove", -16.78, 145.68), ("Daintree ferry", -16.28, 145.32)]),
    ("flinders-ranges-loop", "Flinders Ranges Loop", "oceania", "australia", "south-australia", None,
     210, 6.0, "Off-Road Adventure", "desert", 4, "Apr – Oct",
     "Bunyeroo and Brachina gorge gravel through 800 million years of rock. Willy-wagtails and wedge-tails everywhere.",
     [("Quorn, SA", -32.35, 138.21), ("Wilpena Pound", -31.55, 138.58), ("Parachilna", -31.18, 138.4)]),
    ("milford-road", "Milford Road (Te Anau to Milford Sound)", "oceania", "new-zealand", "southland", None,
     75, 2.5, "Mountain Passes", "mountain", 4, "Nov – Apr",
     "Fiordland's glacial valley run to Milford Sound. Kea parrots dismantle windshields at the Homer Tunnel queue.",
     [("Te Anau", -45.41, 167.72), ("Homer Tunnel", -44.76, 168.13), ("Milford Sound", -44.67, 167.91)]),
    ("crown-range-road", "Crown Range Road", "oceania", "new-zealand", "otago", None,
     22, 0.8, "Hairpin Heaven", "mountain", 3, "Year-round",
     "New Zealand's highest sealed road between Queenstown and Wanaka. Frost in the shaded switchbacks before 10am.",
     [("Arrowtown", -44.94, 168.83), ("Cardrona", -44.83, 168.99), ("Wanaka", -44.7, 169.15)]),
    ("forgotten-world-highway", "Forgotten World Highway", "oceania", "new-zealand", "taranaki", None,
     95, 3.0, "Forest Glide", "mixed", 3, "Nov – Apr",
     "From Stratford to the Whanganui river mouth: one-lane bridges, the Tangarakau gorge, and a hilltop saddle called Whangamomona.",
     [("Stratford, Taranaki", -39.34, 174.29), ("Whangamomona", -39.35, 174.6), ("Taumarunui", -38.86, 175.21)]),
    ("coromandel-loop", "Coromandel Peninsula Loop", "oceania", "new-zealand", "waikato", None,
     120, 4.0, "Scenic Chill", "coastal", 3, "Nov – Apr",
     "The 309 road, Driving Creek's endless gravel hairpins, and Cathedral Cove detours. Kauri groves shade the northern half.",
     [("Thames, NZ", -37.2, 175.44), ("Coromandel Town", -36.76, 175.5), ("Whitianga", -36.82, 175.7)]),
    ("west-coast-wonders", "West Coast Wonders", "oceania", "new-zealand", "west-coast", None,
     200, 6.0, "Long Haul Highway", "forest", 3, "Nov – Apr",
     "Hokitika to Haast: rainforest, one-lane bridges, and the Franz Josef glacier turn-off. Refuel at Fox Glacier, services thin out fast.",
     [("Greymouth", -42.45, 171.21), ("Hokitika", -42.72, 170.96), ("Haast", -43.88, 169.04)]),
]
